Default: &defaults
  database: SharedWorkspace.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: SharedWorkspace_test.sqlite3
  <<: *defaults

Staging:
  database: SharedWorkspace_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: SharedWorkspace_production.sqlite3
  poolsize: 100
  <<: *defaults
